### ISSUE TITLE
Region Color Slider: dropdown does not always appear next to slider

### ISSUE THREAD

**Issue by dkp** [DevinBayly/neuro-choro#10]
A dropdown selector should appear next to the region color column slider. It does not always appear and especially likely to be missing on the first pane.

**Comment by DevinBayly** [comment]
Just a thought. The drop down is populated by the csv that is uploaded, and that data isn't provided immediately on page load. The drop down selector is created upon loading the csv. Would it make more sense if the selection drop down was present but unpopulated with options initially?

The region boundaries are available right when the page loads and a default slice is displayed so the slice slider is included on startup.

The part about how the dropdowns position can change after it first appears, this is related to issue #8, and I believe I know how to fix that as well.

**Comment by dkp** [comment]
I think I'd have to see it to know what you mean. But let's try it.
________________________________

**Comment by DevinBayly** [comment]
Can you take a look at the most recent notebook revision? I believe this issue is resolved. https://alpha.iodide.io/notebooks/3446/?

**Comment by dkp** [comment]
This is great.  You have solved the problem...but see additional issue r colors not showing up.
