### ISSUE TITLE
Region Color Column Slider sometimes fails to display its current location (remains blank)

### ISSUE THREAD

**Issue by dkp** [DevinBayly/neuro-choro#11]
I don't have a picture, but I believe I saw this briefly, so keep your eyes open.

**Comment by DevinBayly** [comment]
I believe this has to do with individual csv files, but there is now a dropdown populated at the start with the suggestion to upload a csv. After that point if a file is uploaded that happens to create a single empty option I don't think it will cause too much concern as folks will know to click and see what other elements are in the drop down. I will keep my eyes out for problems related to this however.
