### ISSUE TITLE
Tile panes 2 across to facilitate comparison

### ISSUE THREAD

**Issue by dkp** [DevinBayly/neuro-choro#13]
Given that comparison is the primary goal, it'd be nice to display 2 panes side by side.

**Comment by DevinBayly** [comment]
Instead of going with a full grid view, I set the panes to wrap when the right side of the screen is encountered. 

![image](https://user-images.githubusercontent.com/11687631/70831045-c7b0f700-1dae-11ea-9ff4-569642c42153.png)

**Comment by DevinBayly** [comment]
Will this facilitate the kind of comparison you were looking for?

**Comment by dkp** [comment]
Yeah, I think this will work fine.  Thanks!
