### ISSUE TITLE
Color does not always appear on map

### ISSUE THREAD

**Issue by dkp** [DevinBayly/neuro-choro#15]
I saw this behavior in Chrome (no color displays on brain map), where I was not able to display the color even though it existed at that slice for that dataset and did display in Firefox.

**Comment by DevinBayly** [comment]
Please double check that this bug is affecting you, chrome on my mac shows colors fine.

**Comment by dkp** [comment]
Never mind, user error (I was displaying a csv for the wrong atlas).  If there was a problem, it appears to be fixed.
