### ISSUE TITLE
legend

### ISSUE THREAD

**Issue by DevinBayly** [DevinBayly/neuro-choro#19]
Have a legend next to the canvas with the color gradient and numerical values associated.

**Comment by DevinBayly** [comment]
this is done.

**Comment by Emrealper445** [comment]
Can you help me out a little bit?

**Comment by Emrealper445** [comment]
I'm a beginner.

**Comment by DevinBayly** [comment]
I could use a bit more context, what part of the tool are you having trouble with? Can you create a specific issue related to what you need help with?
