### ISSUE TITLE
adding legend for color

### ISSUE THREAD

**Issue by DevinBayly** [DevinBayly/neuro-choro#20]
What should be the representation of color in the gradient if both negative and positiev values are in the range of the color column?

**Comment by DevinBayly** [comment]
finished adding color gradient legend.

**Comment by dkp** [comment]
Usually, people use hot for positive values (red to gold) and cool (blues) for negative values. Brighter is more intense (e.g. yellow is brightest, then orange and the reds).
There is a lot less focus on negative values, and you could argue either way (i.e., brighter is more negative or darker is more negative).  I don't have a preference on the negative numbers.
