### ISSUE TITLE
Left align everything

### ISSUE THREAD

**Issue by dkp** [DevinBayly/neuro-choro#21]
The buttons (add pane etc.) should be left-aligned with the text.  The panel should also be left-aligned with the text. 
Obviously a totally minor issue, but it'd look even nicer, I think.

**Comment by DevinBayly** [comment]
I'll revisit this when the more glaring issues are taken care of, but thanks for the suggestion!

**Comment by DevinBayly** [comment]
everything is left aligned by the way. Let me know if I missed something!
