### ISSUE TITLE
Slider too short for giant numbers

### ISSUE THREAD

**Issue by dkp** [DevinBayly/neuro-choro#22]
I processed some data with very large values in the regions. In this case, the slider is too short to accomodate the big numbers.
![Neuro_Choropleth_-_Iodide](https://user-images.githubusercontent.com/965184/70959326-3a350780-2039-11ea-9c27-8fefd54fee43.png)

**Comment by DevinBayly** [comment]
oh gosh look at that! I believe this can probably just be another styling case where the padding was off on the labels. I'll get right to it.

**Comment by DevinBayly** [comment]
![image](https://user-images.githubusercontent.com/11687631/71209502-f6284980-2268-11ea-9937-0ffb89689afc.png)
Now there is spacing provided between the slider labels, Is this enough?

**Comment by DevinBayly** [comment]
Again, let me know if the changes are to your satisfaction @dkp

**Comment by dkp** [comment]
It looks like enough!  Thanks
