### ISSUE TITLE
 Relation of slider and legend unclear

### ISSUE THREAD

**Issue by dkp** [DevinBayly/neuro-choro#23]
I don't understand the behavior of the slider: it starts off blues, I move it around and it switches to reds but seems to have set its own min and max?

The legend also shows a different range than the slider sometimes.
Just a bit weird

**Comment by DevinBayly** [comment]
Ah so I can explain some of the things happening here, and we can figure out how you want it to actually behave. I have resolved the situation where an incorrect color gradient shows briefly upon selecting a fill col filter. The other behavior is consistent, but perhaps not what you were expecting and therefore requires better presentation on the pane.

The fill col filter slider handles range over the min-1 and the max+1 of the selected fill column's values. The gradient legend isn't based on these upper and lower bounds, but could be. Instead the colors used on the gradient and in the regions correspond to the data column post filtration. Take this gradient for example 
![image](https://user-images.githubusercontent.com/11687631/71215537-43aab380-2275-11ea-8070-1e937de3a968.png)

the filter slider is set 1 above the max value of 1000 found in  the selected fill column. This means that the the region of brain that corresponds to the 1000 value should have a fill that matches the top of the gradient. In this way the numerical values in the slider shouldn't match the values shown in the gradient bar.

That said, there is a bug here to work on.0 was always set to be the bottom gradient fill color, but for a dataset that has only values much greater than it, it will be difficult to get any benefit from the color gradient, so I will switch the color gradient to take whatever is the minimum value of the filtered data as the beige/white color.

**Comment by dkp** [comment]
Thanks for the explanation.  You say "The gradient legend isn't based on these upper and lower bounds, but could be." 
I believe the values in the legend should correspond to the ones on the slider.  That way the colors can be set to mean the same thing in two different panes, which will help with comparison.

**Comment by DevinBayly** [comment]
ok, I'll add that right away.

**Comment by DevinBayly** [comment]
Feel free to close this issue if you find the changes to work for you.

**Comment by dkp** [comment]
I think we solved this?  But there are other color issues submitted now.
