### ISSUE TITLE
Readme does not make sense.

### ISSUE THREAD

**Issue by dkp** [DevinBayly/neuro-choro#24]
Choropleths are simple maps that display regional changes as color (e.g., a US map showing states that lean Democrat vs Republican). Here is an example of a brain choropleth.

(Umm, but there is no picture of a choropleth here)

There is more in this readme that does not make sense in this context.
It might make sense to refer people to my read the docs page: https://neuroimaging-core-docs.readthedocs.io/en/latest/pages/choropleths.html

We probably should not refer "Devin Bayly's work" as a work in progress etc. 

You might read it over carefully and decide what works.

**Comment by DevinBayly** [comment]
I've made a few edits since the posting of this issue, please let me know if we can close.

**Comment by dkp** [comment]
Let's close this. If I find any issues with the revised tutorial, I'll let you know.
