### ISSUE TITLE
What does this mean? "Graphs using plotly from the data shown in the imaging panes."

### ISSUE THREAD

**Issue by dkp** [DevinBayly/neuro-choro#25]
I see this statement on the report view...but I have no idea what it means. That is, are you telling us we could create plots with plotly (but with no indication of how to proceed)?
Or are you giving credit to plotly for the choropleths? (This seems unlikely).

Maybe this statement should go away, or maybe you should point to more comprehensive documentation (your code documentation, documentation on adding plotly plots etc.)
Else, I'm really missing something.

**Comment by DevinBayly** [comment]
I can provide some explanation here, but this is related to my point that the choropleth tool should make its data available to programs that are specifically designed for making plots. The wording is misleading you are correct, but I was giving an example of how I used plotly to display data from the choropleth. The reason nothing shows up there is there was no data at the beginning of the notebook's execution (user's upload the csvs or sessions to start). If you explored some data in a pane, then re ran the last section of the notebook's code then a bar plot would show up underneath the misleading text. Needless to say, this isn't part of the finished product and can be removed, but there does need to be some indication the data is available to be made into plots by users and/or graphics libraries accessing the field `.dataForPlot` on the pane object.

**Comment by dkp** [comment]
Perhaps a link to a readme that can provide more info at your leisure...

**Comment by dkp** [comment]
I think this is a long-dead issue.
