### ISSUE TITLE
fetch statement mislabeled?

### ISSUE THREAD

**Issue by dkp** [DevinBayly/neuro-choro#26]
Your code says: ...neuro-choro/**HCP**/src...
but the atlas you have displayed is the HO-CB atlas, so I'm thinking the totalfix.json is not associated with the correct path.  (Note: I am glad the HO-CB atlas is the default)

**Comment by DevinBayly** [comment]
ah not really mislabeled for the fetch, but the branch in the repo tracking much of the current development was the HCP one for a time so I simply grabbed the json where I could find it. The current file will reflect no inclusion of the HCP material for the HO-CB atlas.
