### ISSUE TITLE
Fill Color Filter: 2 grey balls can get confused

### ISSUE THREAD

**Issue by dkp** [DevinBayly/neuro-choro#29]
If you drag the MIN ball on top of the MAX ball, you are in real trouble, you can't tell the difference between them to pull them apart

**Comment by DevinBayly** [comment]
I've added transparency back to them, so you can tell if they are overlapping. they can't get permanently stuck because you simply have to try dragging one way, and the min one won't be able to pass to the right of the max but will be able to move to the left fine. and vice versa.
