### ISSUE TITLE
import messes up fill color filter values that were stored

### ISSUE THREAD

**Issue by DevinBayly** [DevinBayly/neuro-choro#32]
It appears that the values get correctlty passed to the canvas draw, but not the sliders.

![image](https://user-images.githubusercontent.com/11687631/72750413-0427fd80-3b7a-11ea-8295-e61654172ea2.png)

**Comment by dkp** [comment]
It certainly basically works...thanks for being on top of the details!
-Dianne
________________________________

**Comment by DevinBayly** [comment]
fixed now.
