### ISSUE TITLE
Slice Display/Update bug

### ISSUE THREAD

**Issue by dkp** [DevinBayly/neuro-choro#39]
Slice labeled incorrectly:
![Neuro-Choropleth_Tool_DisplayBug](https://user-images.githubusercontent.com/965184/77778458-3e949780-700e-11ea-96f9-4f209f0cbd8a.png)

What I did:
I loaded the same CSV (same as LearnRuns...relabeled as NAD2_Learn_IC2) 4 times, intending to display the 4 runs side by side. All are axial view on slice -6mm.

The Problem: Run2 is different...it should match the others but doesn't.
Additional information: Scrolling from top to bottom, it looks like run2 is the only one that was correct...the others match that slice if I scroll them to the bottom and back up to slice -6. 
In fact, the others were displaying slice 6mm instead of slice -6mm.

**Comment by DevinBayly** [comment]
yikes that's not good. Thanks for all this stress testing I can try to take a look at this before 2pm today.

**Comment by DevinBayly** [comment]
I'm having difficulty recreating this bug. the issue you describe is that the brain slice displayed at the -6mm in run 2's pane is different/wrong compared to the others yes? That's the obvious thing I notice in the picture.

So something got off in the slice selection that got reset to correct when the slider was moved around?

do you think you could recreate this in a screen recording and send it to me?

**Comment by DevinBayly** [comment]
actually I'm pretty sure I see what's happening. It's the brain view radio button that appears to blame. The sagittal slice is correct, but then the switch to axial breaks the connection between the slider's reported value and the canvas picture.

**Comment by DevinBayly** [comment]
let me know if this closes your bug =D

**Comment by dkp** [comment]
It looks like you got it to me!  Thanks!
