### ISSUE TITLE
cartesian product csvs

### ISSUE THREAD

**Issue by DevinBayly** [DevinBayly/neuro-choro#6]
This is a feature request to handle csvs that have multiple references to a region. One example is in the case where there are multiple runs of the data. If this is true, then there would be a column named run and filterable elements within that column to switch between what value is shown at a time. 

Mostly this question relates to what the default aggregate behavior should be when it comes to displaying a column like mean when multiple values exist for one region.

**Comment by DevinBayly** [comment]
default aggregate behavior has been asked to be an average of entries, this is correct yes? @dkp 

If so, the notification a user gets that their particular slice has average data mixed in will look like this.
![image](https://user-images.githubusercontent.com/11687631/70935182-dab90680-1ffc-11ea-91f5-28e274946c9e.png)

Does this hit the nail on the head for how this issue should be handled?

**Comment by dkp** [comment]
This is perfect!  Thank you!
