### ISSUE TITLE
prevent layout shifting

### ISSUE THREAD

**Issue by DevinBayly** [DevinBayly/neuro-choro#8]
The present state of the tool allows for new CSV data to be uploaded, but this causes some elements to be removed and then replaced. The issue is that the position after this operation is not constant. Likely need to have a holder element which doesn't go away that is placed at initialization, and then removal and replacement will not shift position.

**Comment by DevinBayly** [comment]
this is complete as of now

**Comment by dkp** [comment]
Wonderful!
